version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            chmod -R 777 ./tienda-micros      
            brew install pyenv            
            cp ./tienda-micros/users/requirements.txt /home/circleci/project/
          name: Permiso - Copy    
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            pytest ./tienda-micros/users/application_test.py 
            
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
