version: '2'
services:
    users:
        build: users
        ports:
            - "6000:6000"
    orders:
        build: orders
        ports:
            - "7000:7000"
    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        command: [nginx-debug, '-g', 'daemon off;']
        links:
            - users
            - orders
        depends_on: 
            - users
            - orders
        ports:
            - "8080:80" 